name: org_chart
publish_to: none
description: A flutter organizational chart with drag and drop, zoom and pan, search, collapse, expand, and easy customizations!
version: 5.0.3
repository: https://github.com/ahnaineh/org_chart
issue_tracker: https://github.com/ahnaineh/org_chart/issues
homepage: https://ahnaineh.github.io


# publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  custom_interactive_viewer:
    git:
      url: https://github.com/tranvu1805/custom_interactive_viewer.git
    # path: ../custom_interactive_viewer

  pdf: ^3.11.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
